// Date: 2015-01-18 14:12:38
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelPylon Thing extends ModelBase
{
  //fields
    ModelRenderer Layer1;
    ModelRenderer Layer2;
    ModelRenderer Layer3;
  
  public ModelPylon Thing()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Layer1 = new ModelRenderer(this, 0, 0);
      Layer1.addBox(-7F, 3F, -7F, 13, 2, 13);
      Layer1.setRotationPoint(0F, 0F, 0F);
      Layer1.setTextureSize(64, 32);
      Layer1.mirror = true;
      setRotation(Layer1, 0F, 0F, 0F);
      Layer2 = new ModelRenderer(this, 0, 16);
      Layer2.addBox(-5F, 0F, -5F, 9, 2, 9);
      Layer2.setRotationPoint(0F, 0F, 0F);
      Layer2.setTextureSize(64, 32);
      Layer2.mirror = true;
      setRotation(Layer2, 0F, 0F, 0F);
      Layer3 = new ModelRenderer(this, 0, 28);
      Layer3.addBox(-3F, -3F, -3F, 5, 2, 5);
      Layer3.setRotationPoint(0F, 0F, 0F);
      Layer3.setTextureSize(64, 32);
      Layer3.mirror = true;
      setRotation(Layer3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Layer1.render(f5);
    Layer2.render(f5);
    Layer3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
